### ISSUE TITLE
Flash algorithm for ST F401/F091.

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [mbedmicro/FlashAlgo#25]
Is there a flash algorithm available for F401/F091? Where did the algorithm for F411 come from?

@MarceloSalazar

**Comment by MarceloSalazar** [comment]
@sg- it seems you are the maintainer of this repo.
Could you please comment how flash algorithms can be generated to support others MCU, such as F401/F091?

**Comment by sg-** [comment]
There should be a source implementation for the driver. If not, a FLM file can be converted using:
```
<UserProg1Name>..\..\..\scripts\post_build.bat "#KARM\ARMCC\bin\fromelf --bin $L@L.axf -o $L@L" "#KARM\ARMCC\bin\fromelf --text -s $L@L.axf -o $L@L\symbols" "#KARM\ARMCC\bin\armar --create $L@L\@L.ar $L*.o"</UserProg1Name>
```
but there may be licensing problems doing that.

**Comment by markus-becker-tridonic-com** [comment]
@bcostm do you know where the flash algorithms for F411 are from?

**Comment by ashok-rao** [comment]
@sg- , I cloned the FlashAlgo repo, used venv and generated a uVision project. I then (just to test things, without making any changes), built the project in MDK (I have a full licensed version), the project built fine.  I now have a *.hex file & a *.axf from MDK. I can see that MDK runs the exact same command as in your previous comment after a successful build.

Question: Where can I find the FLM file / flash algorithm generated for this? I'm looking to generate the "Flash_Blob" required for porting DAPLink as mentioned here: https://github.com/mbedmicro/DAPLink/blob/master/docs/PORT_TARGET.md 
" A flash algorithm blob is needed to program the target MCUs internal (or external) flash memory. This blob contains position independent functions for erasing, reading and writing to the flash controller. Flash algorithm blobs are created from the FlashAlgo project. An example blob is shown below and would be added to source/target/<mfg>/<targetname>/flash_blob.c "

**Comment by ashok-rao** [comment]
@sg- .. Hit "comment" a bit too soon :-) . I can find the flash_blob under the ."./build/<project_name>" directory. But, looks like this is a *.h file. However, as per instructions here : https://github.com/mbedmicro/DAPLink/blob/master/docs/PORT_TARGET.md , the content of this generated file needs to go into a C file..so, question is what is the content of the 
#include "flash_blob.h" ?

**Comment by ashok-rao** [comment]
@markus-becker-tridonic-com , the flash algorithm is part of the device family pack (DFP) from the vendor. If you have a full version of MDK uVision5, you can download the DFP for the required target from http://www.keil.com/dd2/ , install the DFP and have a look inside the "Flash" directory. For example, I have a Nordic device with me and I can find the FLM files under: <path_to_my_install_dir>\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_DeviceFamilyPack\8.7.1\Flash

I just went and downloaded the DFP for STM32F4xx from the keil link above, installed it and found the FLM under: <path_to_my_install_dir>\Keil_v5\ARM\PACK\Keil\STM32F4xx_DFP\2.10.0\CMSIS\Flash\

You can however generate the flash algo yourself if the device is not supported at all..but you would need a full licensed version of MDK for this and there might be some pack licensing issues from the vendor with that process as well. Have a look here: https://www.keil.com/pack/doc/CMSIS/Pack/html/_flash_algorithm.html for the steps. You can also use this (FlashAlgo) repo to generate the Flash_Blob. You'll need python 2.7.9, a full license of MDK and a few other dependencies..but building from this repo is your last option and should be avoided. Hope this helps.

@MarceloSalazar , @sg- ...anything further you would like to add to this?

**Comment by sg-** [comment]
Thanks @ashok-rao

**Comment by GenericWorkName** [comment]
@ashok-rao Hi, how do I extract for flash blob from the .FLM file?

**Comment by tiantian1645** [comment]
> @ashok-rao Hi, how do I extract for flash blob from the .FLM file?
```
cd FlashAlgo\scripts
python generate_blobs.py path_to_flm_file
```
