### ISSUE TITLE
FTMRE Support / MKE04Z - MKE06Z

### ISSUE THREAD

**Issue by hamedmo** [mbedmicro/FlashAlgo#47]
There is no support for FTMRE flash module. Could you please either add the support or add the flash blob file for the mentioned MCU's? Thank you.

**Comment by flit** [comment]
You can use the `scripts\generate_blobs.py` script in this repo to generate the flash algo blob in multiple formats from the .FLM file in a CMSIS-Pack DFP.

**Comment by hamedmo** [comment]
Thank you for your response. I couldn't find MKE04Z in available CMSIS-Pack DFP's. Is it possible to use other available DFP's, e.g. from Keil?

**Comment by flit** [comment]
If you look on the CMSIS-Pack list (http://www.keil.com/dd2/pack/), there are DFPs for the full KExx series under the NXP section.

**Comment by hamedmo** [comment]
The problem was due to the wrong security bit address in DAPLink. Thanks for the help.
